// Automatically generated by generatorGlobalDts

// GlobalComponents for Volar
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HxRealTime: typeof import('.')['HxRealTime'];
    HxTimepickerDisable: typeof import('.')['HxTimepickerDisable'];
    HxTopologicalGraph: typeof import('.')['HxTopologicalGraph'];
    HxElementTable: typeof import('.')['HxElementTable'];
    HxElementForm: typeof import('.')['HxElementForm'];
    HxPopupWindow: typeof import('.')['HxPopupWindow'];
  }
}

export {};
